### ISSUE TITLE
Motif Database

### ISSUE THREAD

**Issue by imk1** [zeyang-shen/maggie#3]
Thank you for making this fantastic tool!

What motif database do you use?  If I wanted to use my own database, what format do I need to put it in?  Thanks!

**Comment by zeyang-shen** [comment]
Of course you can use your own motif database! 

The default motif database is the **core vertebrates redundant JASPAR database** under the [data](https://github.com/zeyang-shen/maggie/tree/master/data/JASPAR2020_CORE_vertebrates_motifs) folder of our repository. All the motif files were originally downloaded from the [JASPAR website](https://jaspar.genereg.net/downloads/) in the **JASPAR format**. See an example here for SPI1 motif: [MA0080.4.jaspar](https://github.com/zeyang-shen/maggie/blob/master/data/JASPAR2020_CORE_vertebrates_motifs/MA0080.4.jaspar). JASPAR format stores counts, so if you start with probabilities, you can convert probabilities to counts by multiplying a large number (e.g., 1000). 

If you happen to have motif files in the [HOMER format](http://homer.ucsd.edu/homer/motif/creatingCustomMotifs.html), we have a custom function to convert HOMER motif files to JASPAR format: https://github.com/zeyang-shen/maggie/blob/808782038db47e9e5d24b94d1f461b50e2a6a03e/maggie/utils.py#L299
